#!/bin/bash
# MSK MIND Claude Plugins
# https://github.com/msk-mind/claude-plugins

echo "MSK MIND Claude Plugins"
echo "======================="
echo ""
echo "Installation:"
echo ""
echo "  claude plugin marketplace add msk-mind/claude-plugins"
echo "  claude plugin install jira-toolkit@msk-mind-plugins"
echo "  claude plugin install confluence-toolkit@msk-mind-plugins"
echo ""
echo "Configuration:"
echo ""
echo "  Create ~/.atlassian_env with:"
echo ""
echo "    # For Jira"
echo "    export JIRA_URL=https://your-domain.atlassian.net"
echo "    export JIRA_API_TOKEN=your-api-token"
echo ""
echo "    # For Confluence"
echo "    export CONFLUENCE_URL=https://your-confluence.example.com/"
echo "    export CONFLUENCE_USERNAME=your-username"
echo "    export CONFLUENCE_API_TOKEN=your-api-token"
echo ""
echo "  Then: chmod 600 ~/.atlassian_env"
echo ""
echo "Restart Claude Code after installation."
